### ISSUE TITLE
i can't add it to my laravel 8 / 9 projects

### ISSUE THREAD

**Issue by salahdidi** [laravel-workflow/waterline#1]
![image](https://user-images.githubusercontent.com/104596961/203754735-b4d333ea-f5f2-4a43-952b-0566f1fa4e8f.png)

**Comment by rmcdaniel** [comment]
Thanks for your report! I haven't tested it with Laravel 8. Currently the minimum supported version is 9 and it looks like you're using a beta version of 9? Give me some time and I'll see if Laravel 8 works or how difficult it would be to make it work. However, if at all possible, upgrading to the latest version of Laravel 9 would be the best way to go, since you'll get the benefits of upgrading too. Sorry for the inconvenience! I'll leave this issue open until I either add support for Laravel 8 or determine if it can't easily be done. I'll update it once I figure it out. Thanks again!

**Comment by salahdidi** [comment]
i will upgrade it to 9 idk why it beta  , thx for the answer

**Comment by salahdidi** [comment]
it did work with larael 9 i just updated the version of laravel from beta to 9.41
